### ISSUE TITLE
datasette jupyterlite IndexError: list index out of range

### ISSUE THREAD

**Issue by ctsrc** [simonw/datasette-jupyterlite#5]
Hi, 

I installed `datasette-jupyterlite` with the following command:

```zsh
datasette install datasette-jupyterlite
```

And now when I try to run `datasette` it gets an `IndexError`:

```text
Traceback (most recent call last):
  File "/opt/homebrew/bin/datasette", line 5, in <module>
    from datasette.cli import cli
  File "/opt/homebrew/Cellar/datasette/0.64.3_1/libexec/lib/python3.11/site-packages/datasette/cli.py", line 17, in <module>
    from .app import (
  File "/opt/homebrew/Cellar/datasette/0.64.3_1/libexec/lib/python3.11/site-packages/datasette/app.py", line 30, in <module>
    from .views.database import DatabaseDownload, DatabaseView
  File "/opt/homebrew/Cellar/datasette/0.64.3_1/libexec/lib/python3.11/site-packages/datasette/views/database.py", line 27, in <module>
    from datasette.plugins import pm
  File "/opt/homebrew/Cellar/datasette/0.64.3_1/libexec/lib/python3.11/site-packages/datasette/plugins.py", line 27, in <module>
    pm.load_setuptools_entrypoints("datasette")
  File "/opt/homebrew/Cellar/datasette/0.64.3_1/libexec/lib/python3.11/site-packages/pluggy/_manager.py", line 364, in load_setuptools_entrypoints
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/datasette/0.64.3_1/libexec/lib/python3.11/site-packages/datasette_jupyterlite/__init__.py", line 8, in <module>
    tarpath = list(files("jupyterlite").glob("*.tgz"))[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by Darkle** [comment]
I'm also getting this issue.
